#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
This project is licensed under the New BSD License:

Copyright (c) 2012, Pierre-Yves Chibon

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.
* Neither the name of the Wageningen University nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ''AS IS'' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
THE POSSIBILITY OF SUCH DAMAGE.
"""

"""
This script retrieve the bibtex entries for PubMed identifier given.
"""


import argparse
import logging
import requests


def setup_parser():
    """ Set the main arguments. """
    parser = argparse.ArgumentParser(prog='pmid2bibtex')
    parser.add_argument('pmid', nargs='+',
                    help = 'PubMed identifier(s)')
    return parser

def extract_references(content):
    output = ""
    flag = False
    for line in content.split('\n'):
        if '<pre>' in line.lower():
            flag = True
            continue
        if '</pre>' in line.lower():
            flag = False
            break
        if flag:
            output = output + '\n' + line
    return output

if __name__ == '__main__':
    parser = setup_parser()
    args = parser.parse_args()
    pmids = ','.join(args.pmid)
    r = requests.get(
        'http://www.bioinformatics.org/texmed/cgi-bin/list.cgi?PMID=%s' % pmids)
    print extract_references(r.content)
    
